"""empty message

Revision ID: 175235720f56
Revises: 61fd7b1a6054
Create Date: 2020-12-14 13:59:25.369944

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '175235720f56'
down_revision = '61fd7b1a6054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estacao', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('estacao', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estacao', 'updated_on')
    op.drop_column('estacao', 'created_on')
    # ### end Alembic commands ###
