"""empty message

Revision ID: 27922362fa3a
Revises: 
Create Date: 2020-11-13 16:04:49.585371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27922362fa3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('params', sa.String(length=255), nullable=False),
    sa.Column('estacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estacao_id'], ['estacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('datahora', sa.DateTime(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leitura')
    op.drop_table('sensor')
    op.drop_table('user')
    op.drop_table('estacao')
    # ### end Alembic commands ###
