"""empty message

Revision ID: 61fd7b1a6054
Revises: 3eeb4ae85a13
Create Date: 2020-11-30 14:31:27.250926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fd7b1a6054'
down_revision = '3eeb4ae85a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth', 'is_admin')
    # ### end Alembic commands ###
